<a href="https://colab.research.google.com/github/davidkorea/google_colaboratory/blob/master/forward_backward_prop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import random

In [0]:
N = 20
dimensions = [10, 5, 10]
data = np.random.randn(N, dimensions[0])   # each row will be a datum
labels = np.zeros((N, dimensions[2]))
for i in range(N):
    labels[i, random.randint(0,dimensions[2]-1)] = 1

params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
    dimensions[1] + 1) * dimensions[2], )

In [10]:
(dimensions[0] + 1) * dimensions[1] + (
    dimensions[1] + 1) * dimensions[2]

115

In [6]:
data.shape

(20, 10)

In [7]:
labels

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [9]:
params.shape

(115,)

In [11]:
params

array([ 3.50149115e-01,  1.10782969e+00,  8.46282871e-01, -2.12331050e-01,
       -7.18801999e-01,  2.41575648e+00, -4.25350598e-01, -6.34230923e-01,
        5.67461363e-02, -4.21419311e-01,  3.14121654e-01, -1.56601316e+00,
        6.70359676e-01, -8.98870229e-01,  1.67312956e+00, -1.72370731e+00,
       -1.13225767e+00,  5.96975320e-01, -2.54969604e-01,  9.34719826e-01,
        1.26775007e-01,  2.99160768e-01, -1.14151698e-01,  6.15052814e-01,
        2.30617104e+00, -5.89336736e-01, -6.62581000e-02, -5.93743464e-01,
       -1.26097556e+00,  4.43998139e-01, -7.69904124e-01,  6.86751335e-01,
        4.88354331e-02,  1.28084297e+00, -1.42302147e+00, -5.53330278e-01,
       -4.31515353e-01,  9.95691809e-01,  5.78719971e-01,  1.04663424e+00,
        7.36117949e-01, -7.63258229e-01, -1.72386277e+00,  1.99223582e-01,
        2.03256132e+00, -1.75120825e+00,  3.83870222e-01, -4.63779262e-01,
        2.12580257e-01, -2.10892375e-01,  8.26726352e-01, -2.87825635e-01,
        1.15888911e+00, -

In [12]:
np.reshape(params[0:6],(2,3))

array([[ 0.35014911,  1.10782969,  0.84628287],
       [-0.21233105, -0.718802  ,  2.41575648]])