<a href="https://colab.research.google.com/github/davidkorea/google_colaboratory/blob/master/forward_backward_prop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import random

In [0]:
N = 20
dimensions = [10, 5, 10]
data = np.random.randn(N, dimensions[0])   # each row will be a datum
labels = np.zeros((N, dimensions[2]))
for i in range(N):
    labels[i, random.randint(0,dimensions[2]-1)] = 1

params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
    dimensions[1] + 1) * dimensions[2], )

In [10]:
(dimensions[0] + 1) * dimensions[1] + (
    dimensions[1] + 1) * dimensions[2]

115

In [6]:
data.shape

(20, 10)

In [7]:
labels

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [9]:
params.shape

(115,)

In [11]:
params

array([ 3.50149115e-01,  1.10782969e+00,  8.46282871e-01, -2.12331050e-01,
       -7.18801999e-01,  2.41575648e+00, -4.25350598e-01, -6.34230923e-01,
        5.67461363e-02, -4.21419311e-01,  3.14121654e-01, -1.56601316e+00,
        6.70359676e-01, -8.98870229e-01,  1.67312956e+00, -1.72370731e+00,
       -1.13225767e+00,  5.96975320e-01, -2.54969604e-01,  9.34719826e-01,
        1.26775007e-01,  2.99160768e-01, -1.14151698e-01,  6.15052814e-01,
        2.30617104e+00, -5.89336736e-01, -6.62581000e-02, -5.93743464e-01,
       -1.26097556e+00,  4.43998139e-01, -7.69904124e-01,  6.86751335e-01,
        4.88354331e-02,  1.28084297e+00, -1.42302147e+00, -5.53330278e-01,
       -4.31515353e-01,  9.95691809e-01,  5.78719971e-01,  1.04663424e+00,
        7.36117949e-01, -7.63258229e-01, -1.72386277e+00,  1.99223582e-01,
        2.03256132e+00, -1.75120825e+00,  3.83870222e-01, -4.63779262e-01,
        2.12580257e-01, -2.10892375e-01,  8.26726352e-01, -2.87825635e-01,
        1.15888911e+00, -

In [12]:
np.reshape(params[0:6],(2,3))

array([[ 0.35014911,  1.10782969,  0.84628287],
       [-0.21233105, -0.718802  ,  2.41575648]])

In [0]:
def gradcheck_naive(f, x):
    """ Gradient check for a function f.

    Arguments:
    f -- a function that takes a single argument and outputs the
         cost and its gradients
    x -- the point (numpy array) to check the gradient at
    """

    rndstate = random.getstate()
    random.setstate(rndstate)
#     fx, grad = f(x) # Evaluate function value at original point
    h = 1e-4        # Do not change this!

    # Iterate over all indexes ix in x to check the gradient.
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        ix = it.multi_index

        # Try modifying x[ix] with h defined above to compute numerical
        # gradients (numgrad).

        # Use the centered difference of the gradient.
        # It has smaller asymptotic error than forward / backward difference
        # methods. If you are curious, check out here:
        # https://math.stackexchange.com/questions/2326181/when-to-use-forward-or-central-difference-approximations

        # Make sure you call random.setstate(rndstate)
        # before calling f(x) each time. This will make it possible
        # to test cost functions with built in randomness later.

        ### YOUR CODE HERE:
        # raise NotImplementedError
        # 对矩阵中的每一个元素，+一个很小的数，在-一个很小的数，除以2倍这个很小的数。
        # 再还原该元素在矩阵中的原始值
        old_val = x[ix]
        x[ix] = old_val - h
        random.setstate(rndstate)
        fxh1 = f(x)
        
        x[ix] = old_val + h
        random.setstate(rndstate)
        fxh2 = f(x)

        numgrad = (fxh2 - fxh1)/(2*h)
        x[ix] = old_val

        ### END YOUR CODE

        # Compare gradients
#         reldiff = abs(numgrad - grad[ix]) / max(1, abs(numgrad), abs(grad[ix]))
#         if reldiff > 1e-5:
#             print ("Gradient check failed.")
#             print ("First gradient error found at index %s" % str(ix))
#             print ("Your gradient: %f \t Numerical gradient: %f" % (
#                 grad[ix], numgrad))
#             return

        it.iternext() # Step to next dimension

#     print ("Gradient check passed!")
    return numgrad


In [0]:
def sigmoid(x):
    """
    Compute the sigmoid function for the input here.

    Arguments:
    x -- A scalar or numpy array.

    Return:
    s -- sigmoid(x)
    """

    s = 1 / (1 + np.exp(-x))
    return s

In [0]:
def softmax(x):
    """Compute the softmax function for each row of the input x.

    It is crucial that this function is optimized for speed because
    it will be used frequently in later code. You might find numpy
    functions np.exp, np.sum, np.reshape, np.max, and numpy
    broadcasting useful for this task.

    Numpy broadcasting documentation:
    http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

    You should also make sure that your code works for a single
    D-dimensional vector (treat the vector as a single row) and
    for N x D matrices. This may be useful for testing later. Also,
    make sure that the dimensions of the output match the input.

    You must implement the optimization in problem 1(a) of the
    written assignment!

    Arguments:
    x -- A D dimensional vector or N x D dimensional numpy matrix.

    Return:
    x -- You are allowed to modify x in-place
    """
    orig_shape = x.shape
    soft_max_list = []
    if len(x.shape) > 1:
        # Matrix
        ### YOUR CODE HERE
        for i in range(x.shape[0]): #rows
          soft_max_row = []
          row = x[i]
          argmax = np.argmax(row)
          max_i = row[argmax]
          exp_max_row = np.exp(row-max_i)
          down = np.sum(exp_max_row)
          for j in range(x.shape[1]):
            up = exp_max_row[j]
            soft_max_i = up / down
            soft_max_row.append(soft_max_i)
          soft_max_list.append(soft_max_row)
#         raise NotImplementedError
        ### END YOUR CODE
    else:
        # Vector
        ### YOUR CODE HERE
        argmax = np.argmax(x)
        max_i = x[argmax]
        exp_max_x = np.exp(x-max_i)
        down = np.sum(exp_max_x)
        for i in range(x.shape[0]):
          up = exp_max_x[i]
          soft_max_i = up / down
          soft_max_list.append(soft_max_i)
#         raise NotImplementedError
        ### END YOUR CODE

    assert x.shape == np.array(soft_max_list).shape
    return np.array(soft_max_list)

In [0]:
def forward_backward_prop(X, labels, params, dimensions):
    """
    Forward and backward propagation for a two-layer sigmoidal network

    Compute the forward propagation and for the cross entropy cost,
    the backward propagation for the gradients for all parameters.

    Notice the gradients computed here are different from the gradients in
    the assignment sheet: they are w.r.t. weights, not inputs.

    Arguments:
    X -- M x Dx matrix, where each row is a training example x.
    labels -- M x Dy matrix, where each row is a one-hot vector.
    params -- Model parameters, these are unpacked for you.
    dimensions -- A tuple of input dimension, number of hidden units
                  and output dimension
    """

    ### Unpack network parameters (do not modify)
    ofs = 0
    Dx, H, Dy = (dimensions[0], dimensions[1], dimensions[2])

    W1 = np.reshape(params[ofs:ofs+ Dx * H], (Dx, H))
    ofs += Dx * H
    b1 = np.reshape(params[ofs:ofs + H], (1, H))
    ofs += H
    W2 = np.reshape(params[ofs:ofs + H * Dy], (H, Dy))
    ofs += H * Dy
    b2 = np.reshape(params[ofs:ofs + Dy], (1, Dy))

    # Note: compute cost based on `sum` not `mean`.
    ### YOUR CODE HERE: forward propagation
    # raise NotImplementedError
    a1 = sigmoid(np.dot(X, W1) + b1)
    a2 = softmax(np.dot(a1, W2) + b2)
    
    cost = -np.sum(labels * np.log(a2))
    # - np.sum(np.log(a2[labels == 1]))
    ### END YOUR CODE

    ### YOUR CODE HERE: backward propagation
    # raise NotImplementedError
    loss_w = lambda w: cost
    grad = {}
    grad['w1'] = gradcheck_naive(loss_w,W1)
    grad['b1'] = gradcheck_naive(loss_w,b1)
    grad['w2'] = gradcheck_naive(loss_w,W2)
    grad['b2'] = gradcheck_naive(loss_w,b1)
    
    ### END YOUR CODE

    ### Stack gradients (do not modify)
#     grad = np.concatenate((gradW1.flatten(), gradb1.flatten(),
#         gradW2.flatten(), gradb2.flatten()))

    return cost, grad

In [0]:
# def sanity_check():
#     """
#     Set up fake data and parameters for the neural network, and test using
#     gradcheck.
#     """
#     print ("Running sanity check...")

N = 20
dimensions = [10, 5, 10]
data = np.random.randn(N, dimensions[0])   # each row will be a datum
labels = np.zeros((N, dimensions[2]))
for i in range(N):
    labels[i, random.randint(0,dimensions[2]-1)] = 1

params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
    dimensions[1] + 1) * dimensions[2], )

#     gradcheck_naive(lambda params:
#         forward_backward_prop(data, labels, params, dimensions), params)


In [39]:
forward_backward_prop(data, labels, params, dimensions)

(92.58644044107878, {'b1': 0.0, 'b2': 0.0, 'w1': 0.0, 'w2': 0.0})