<a href="https://colab.research.google.com/github/davidkorea/google_colaboratory/blob/master/numpy_dot_star_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

  
# Vector
  1. ** a * b **: same location element product, return same shape as input
  2. ** np.dot(a, b)**:  one scalar，A numer (1row, 1col)
    $$  \vec a \cdot \vec b=\sum_{i-1}^{n} a_i  b_i$$
     $$  \vec a \cdot \vec b= |a| |b| cos \theta $$
  
  
# Matrix
  1. ** a * b **, **same shape ONLY**: same location element product, return same shape as input
  2.   ** np.dot(a, b)**: each row of a product each column of b, return (a.shape[0], b.shape[1])

# 1. Vector numpy * vs numpy dot

In [3]:
a = np.array([1,2])
a

array([1, 2])

In [25]:
b = np.array([3,4])
b

array([3, 4])

In [26]:
np.dot(a,b)

11

In [27]:
a*b

array([3, 8])

# 2. Matric numpy * vs numpy dot 

In [14]:
c = np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [33]:
d = np.array([[1,1],[0,1]])
d

array([[1, 1],
       [0, 1]])

In [34]:
c * d

array([[1, 2],
       [0, 4]])

In [35]:
np.dot(c,d)

array([[1, 3],
       [3, 7]])

In [36]:
e = np.array([[1,1,1],[0,1,1]])
e

array([[1, 1, 1],
       [0, 1, 1]])

In [37]:
np.dot(c,e)

array([[1, 3, 3],
       [3, 7, 7]])