<a href="https://colab.research.google.com/github/davidkorea/google_colaboratory/blob/master/softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [31]:
a = np.array([[1,2],[4,3],[10,6]])
a.shape

(3, 2)

In [7]:
a.shape[0]

3

In [10]:
row = a[0]
row

array([1, 2])

In [11]:
row[np.argmax(a[0])]

2

In [14]:
exp = np.exp(row-2)
exp

array([0.36787944, 1.        ])

In [15]:
np.sum(exp)

1.3678794411714423

In [72]:
b = np.array([1,2,3])
b.shape

(3,)

In [74]:
b.shape[0]

3

In [76]:
b[np.argmax(b)]

3

In [59]:
 np.exp(b-3)

array([[0.13533528, 0.36787944, 1.        ]])

In [0]:
def softmax(x):
  soft_max_list = []
  if len(x.shape) > 1:
    for i in range(x.shape[0]): #rows
      soft_max_row = []
      row = x[i]
      argmax = np.argmax(row)
      max_i = row[argmax]
      exp_max_row = np.exp(row-max_i)
      down = np.sum(exp_max_row)
      for j in range(x.shape[1]):
        up = exp_max_row[j]
        soft_max_i = up / down
        soft_max_row.append(soft_max_i)
      soft_max_list.append(soft_max_row)

  else:
    argmax = np.argmax(x)
    max_i = x[argmax]
    exp_max_x = np.exp(x-max_i)
    down = np.sum(exp_max_x)
    for i in range(x.shape[0]):
      up = exp_max_x[i]
      soft_max_i = up / down
      soft_max_list.append(soft_max_i)
#   print(soft_max_list)
  return soft_max_list

In [87]:
softmax(a)

[[0.2689414213699951, 0.7310585786300049],
 [0.7310585786300049, 0.2689414213699951],
 [0.9820137900379085, 0.017986209962091555]]

In [88]:
softmax(b)

[0.09003057317038046, 0.24472847105479764, 0.6652409557748218]

In [67]:
softmax(np.array([[1,2]]))

[0.2689414213699951, 0.7310585786300049]

In [0]:
import numpy as np


def softmax(x):
    """Compute the softmax function for each row of the input x.

    It is crucial that this function is optimized for speed because
    it will be used frequently in later code. You might find numpy
    functions np.exp, np.sum, np.reshape, np.max, and numpy
    broadcasting useful for this task.

    Numpy broadcasting documentation:
    http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

    You should also make sure that your code works for a single
    D-dimensional vector (treat the vector as a single row) and
    for N x D matrices. This may be useful for testing later. Also,
    make sure that the dimensions of the output match the input.

    You must implement the optimization in problem 1(a) of the
    written assignment!

    Arguments:
    x -- A D dimensional vector or N x D dimensional numpy matrix.

    Return:
    x -- You are allowed to modify x in-place
    """
    orig_shape = x.shape
    soft_max_list = []
    if len(x.shape) > 1:
        # Matrix
        ### YOUR CODE HERE
        for i in range(x.shape[0]): #rows
          soft_max_row = []
          row = x[i]
          argmax = np.argmax(row)
          max_i = row[argmax]
          exp_max_row = np.exp(row-max_i)
          down = np.sum(exp_max_row)
          for j in range(x.shape[1]):
            up = exp_max_row[j]
            soft_max_i = up / down
            soft_max_row.append(soft_max_i)
          soft_max_list.append(soft_max_row)
#         raise NotImplementedError
        ### END YOUR CODE
    else:
        # Vector
        ### YOUR CODE HERE
        argmax = np.argmax(x)
        max_i = x[argmax]
        exp_max_x = np.exp(x-max_i)
        down = np.sum(exp_max_x)
        for i in range(x.shape[0]):
          up = exp_max_x[i]
          soft_max_i = up / down
          soft_max_list.append(soft_max_i)
#         raise NotImplementedError
        ### END YOUR CODE

    assert x.shape == np.array(soft_max_list).shape
    return np.array(soft_max_list)


def test_softmax_basic():
    """
    Some simple tests to get you started.
    Warning: these are not exhaustive.
    """
    print( "Running basic tests...")
    test1 = softmax(np.array([1,2]))
    print( test1)
    ans1 = np.array([0.26894142,  0.73105858])
    assert np.allclose(test1, ans1, rtol=1e-05, atol=1e-06)

    test2 = softmax(np.array([[1001,1002],[3,4]]))
    print( test2)
    ans2 = np.array([
        [0.26894142, 0.73105858],
        [0.26894142, 0.73105858]])
    assert np.allclose(test2, ans2, rtol=1e-05, atol=1e-06)

    test3 = softmax(np.array([[-1001,-1002]]))
    print( test3)
    ans3 = np.array([0.73105858, 0.26894142])
    assert np.allclose(test3, ans3, rtol=1e-05, atol=1e-06)

    print( "You should be able to verify these results by hand!\n")


def test_softmax():
    """
    Use this space to test your softmax implementation by running:
        python q1_softmax.py
    This function will not be called by the autograder, nor will
    your tests be graded.
    """
    print( "Running your tests...")
    ### YOUR CODE HERE
    raise NotImplementedError
    ### END YOUR CODE


# if __name__ == "__main__":
#     test_softmax_basic()
#     test_softmax()


In [98]:
test_softmax_basic()

Running basic tests...
[0.26894142 0.73105858]
[[0.26894142 0.73105858]
 [0.26894142 0.73105858]]
[[0.73105858 0.26894142]]
You should be able to verify these results by hand!



[[0.73105858 0.26894142]]
You should be able to verify these results by hand!



In [101]:
|

NotImplementedError: ignored